### ISSUE TITLE
add photos and press tabs to media page

### ISSUE THREAD

**Issue by caxy4** [caxy4/ezza_rose#31]
- [x] styling for each page
- [x] mobile styling for each page

**Comment by caxy4** [comment]
got this up on the test site with styling for all but the press page because i'm not sure what the content is going to be like exactly

@ezzarose can you give me a few examples of what "press" will be?
Also take a look at the [test site](http://test.ezzarose.com/media/) and let me know what you think

**Comment by caxy4** [comment]
Closing as the changes for the media page have been pushed live.

**Comment by ezzarose** [comment]
I was thinking press would be just text, like the homepage blog. I think
the videos look good. I'm working on getting the photos resized for the
band bio section, the guys are trying to track down originals so I can size
them down.



On Wed, Jan 7, 2015 at 1:03 AM, Alex Ellison <notifications@github.com>
wrote:

> got this up on the test site with styling for all but the press page
> because i'm not sure what the content is going to be like exactly
>
> @ezzarose <https://github.com/ezzarose> can you give me a few examples of
> what "press" will be?
> Also take a look at the test site <http://test.ezzarose.com/media/> and
> let me know what you think
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caxy4/ezza_rose/issues/31#issuecomment-68994900>.
>



-- 
*Ezza Rose Management*
www.ezzarose.com <http://ezzarose.com>

*New Album: **When the Water's Hot*
<http://ezzarose.bandcamp.com/album/when-the-waters-hot> (released January
17, 2015)

*Bandcamp:* ezzarose.bandcamp.com
*Pandora:* pandora.com/ezza-rose
*CD Baby: *cdbaby.com/artist/ezzarose <http://cdbaby.com/Artist/EzzaRose>

*Facebook: *facebook.com/ezzarosemusic
*Twitter: *@ezzaroseband
